<?php
$productos = [
          0=>["acti"=>"active",
              "imagen"=>"producto1a.jpg",
              "titulo"=>"Modelo Niza",
              "descp"=>"Some small description goes here",
              "rating"=>[122 . " views", 199 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],
          1=>["acti"=>"active",
              "imagen"=>"producto2a.jpg",
              "titulo"=>"Modelo Punta del Este",
              "descp"=>"Some small description goes here",
              "rating"=>[117 . " views", 201 . " likes"],
              "pricenew"=>"$580",
              "priceold"=>"$1180"],
          2=>["acti"=>"active",
              "imagen"=>"producto3o.jpg",
              "titulo"=>"Modelo Bali",
              "descp"=>"Some small description goes here",
              "rating"=>[132 . " views", 289 . " likes"],
              "pricenew"=>"$720",
              "priceold"=>"$1380"],
          3=>["acti"=>"active",
              "imagen"=>"producto4o.jpg",
              "titulo"=>"Modelo Texas",
              "descp"=>"Some small description goes here",
              "rating"=>[56 . " views", 112 . " likes"],
              "pricenew"=>"$420",
              "priceold"=>"$980"],
          4=>["acti"=>"active",
              "imagen"=>"producto5a.jpg",
              "titulo"=>"Modelo New York",
              "descp"=>"Some small description goes here",
              "rating"=>[80 . " views", 232 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],
          5=>["acti"=>"active",
              "imagen"=>"producto6.jpg",
              "titulo"=>"Modelo Madrid",
              "descp"=>"Some small description goes here",
              "rating"=>[99 . " views", 167 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],
          6=>["acti"=>"active",
              "imagen"=>"producto7.jpg",
              "titulo"=>"Modelo Hombre 1",
              "descp"=>"Some small description goes here",
              "rating"=>[55 . " views", 144 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],
          7=>["acti"=>"active",
              "imagen"=>"producto8.jpg",
              "titulo"=>"Modelo Hombre 2",
              "descp"=>"Some small description goes here",
              "rating"=>[44 . " views", 112 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],
          8=>["acti"=>"active",
              "imagen"=>"producto9.jpeg",
              "titulo"=>"Modelo Hombre 3",
              "descp"=>"Some small description goes here",
              "rating"=>[80 . " views", 124 . " likes"],
              "pricenew"=>"$1280",
              "priceold"=>"$1980"],

              ];


 ?>
